### ISSUE TITLE
[Bug] removeAllListeners does not work

### ISSUE THREAD

**Issue by Reizar** [sultanmyrza/preview-camera#25]
Hi,

My code looks something like this: 

```javascript

  useEffect(() => {
    PreviewCamera.addListener('capturePhotoFinished', handlePhotoCaptured);
    PreviewCamera.addListener('captureVideoFinished', handleVideoCaptured);

    return () => {
      PreviewCamera.removeAllListeners();
    };
  }, [handlePhotoCaptured, handleVideoCaptured]);
```

However, the removeEventListeners call doesn't actually work, and leads to the callback function being called multiple times as the useEffect hook gets re-run. 

The logs in xCode show this output:

```
⚡️  To Native ->  PreviewCamera removeAllListeners 20568578
⚡️  Error calling method removeAllListeners on plugin PreviewCamera: No method found.
⚡️  Ensure plugin method exists and uses @objc in its declaration, and has been defined
```

**Comment by sultanmyrza** [comment]
@Reizar, thank you for reporting the issue. I will create simple react app and try to re-produce your case.

**Comment by sultanmyrza** [comment]
@Reizar, fixed. Please try to install version 0.0.18 or [above](https://github.com/sultanmyrza/preview-camera/releases). In your project you can try
1. `npm r @numbersprotocol/preview-camera` (completely removes plugin)
1. `npm i git+https://github.com/sultanmyrza/preview-camera.git#0.0.18`  (since I haven't published to npm you need to install from git directly)

I also added [react-example](https://github.com/sultanmyrza/preview-camera/tree/main/example/react) for reference. In react-example I use ionic [lifecycle hooks](https://github.com/sultanmyrza/preview-camera/blob/dcf88052a75c3c27a2a11b749a16e0fc8aeb5799/example/react/src/pages/CameraPage.tsx#L204). Here is the [demo preview](https://github.com/sultanmyrza/preview-camera/assets/12681781/e5de0b50-f6d4-43fd-9b00-52e445734829). Please let me know if you got it working on your side.

**Comment by Reizar** [comment]
Hi @sultanmyrza ,

That fixed the issue. Many thanks for pushing this up, its much appreciated.
